etc/proxmox-backup.service /lib/systemd/system/
etc/proxmox-backup-proxy.service /lib/systemd/system/
usr/lib/x86_64-linux-gnu/proxmox-backup/proxmox-backup-api
usr/lib/x86_64-linux-gnu/proxmox-backup/proxmox-backup-proxy
usr/share/man/man1/proxmox-backup-proxy.1
usr/sbin/proxmox-backup-manager
usr/share/man/man1/proxmox-backup-manager.1
usr/share/javascript/proxmox-backup/js/proxmox-backup-gui.js
usr/share/javascript/proxmox-backup/images/logo-128.png
usr/share/javascript/proxmox-backup/images/proxmox_logo.png
usr/share/javascript/proxmox-backup/css/ext6-pbs.css